version: '3.0'
services:
  crawler:
    build: crawler
    image: crawler
    user: $USER_ID:$GROUP_ID
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./crawler:/usr/src/app
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    env_file:
      - .env
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb