version: '3.0'

networks:
  ptixiakiErgasia:

services:
  mariadb:
    image: mariadb
    # restart: always #Commented due to auto start on boot of dev machine
    volumes:
      - ./database:/var/lib/mysql
    env_file:
      - .env
    networks:
      ptixiakiErgasia:
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MARIADB_ROOT_PASSWORD
      interval: 4s
      timeout: 2s
      retries: 5
  backend:
    build: backend
    image: backend
    user: $USER_ID:$GROUP_ID
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      ptixiakiErgasia:
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      mariadb:
        condition: service_healthy
  frontend:
    build: frontend
    image: frontend
    ports:
      - "8080:80"
    networks:
      ptixiakiErgasia:
    depends_on:
      - backend
  # phpmyadmin:
  #   image: phpmyadmin
  #   # restart: always #Commented due to auto start on boot of dev machine
  #   ports:
  #     - 8080:80
  #   networks:
  #     ptixiakiErgasia:
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOST=mariadb
  #   depends_on:
  #     mariadb:
  #       condition: service_healthy