version: '3.0'

networks:
  ptixiakiErgasiaNetwork:
    name: ptixiaki_ergasia_network

services:
  mariadb:
    image: mariadb
    container_name: ptixiaki_ergasia_db
    # restart: always #Commented due to auto start on boot of dev machine
    volumes:
      - ./database:/var/lib/mysql
    env_file:
      - .env
    networks:
      - ptixiakiErgasiaNetwork
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MARIADB_ROOT_PASSWORD
      interval: 4s
      timeout: 2s
      retries: 5