version: '3.0'
services:
  backend:
    build: backend
    image: backend
    user: $USER_ID:$GROUP_ID
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    image: mariadb
    # restart: always #Commented due to auto start on boot of dev machine
    volumes:
      - ./database:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MARIADB_ROOT_PASSWORD
      interval: 4s
      timeout: 2s
      retries: 5
  # phpmyadmin:
  #   image: phpmyadmin
  #   # restart: always #Commented due to auto start on boot of dev machine
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOST=mariadb
  #   depends_on:
  #     mariadb:
  #       condition: service_healthy